#!/bin/bash
python3 trieTester.py test1
sleep 1
python3 trieTester.py test2
sleep 1
python3 trieTester.py test3
sleep 1
python3 trieTester.py test4
sleep 1
python3 trieTester.py test5
sleep 1
python3 trieTester.py test6
sleep 1
python3 trieTester.py test7
sleep 1
python3 trieTester.py test8
sleep 1
python3 trieTester.py test9
